// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Responder.Droid.firehall.net {
    
}


[System.ServiceModel.ServiceContractAttribute(Namespace="Responder.Droid.firehall.net", ConfigurationName="WebService1Soap")]
public interface WebService1Soap {
    
    [System.ServiceModel.OperationContractAttribute(Action="*", ReplyAction="http://tempuri.org/Responding")]
    string Responding(string sCompanyID, string sDeviceID, decimal dLatitude, decimal dLongitude);
    
    [System.ServiceModel.OperationContractAttribute(Action="*", ReplyAction="http://tempuri.org/Responding", AsyncPattern=true)]
    System.IAsyncResult BeginResponding(string sCompanyID, string sDeviceID, decimal dLatitude, decimal dLongitude, System.AsyncCallback asyncCallback, object userState);
    
    string EndResponding(System.IAsyncResult result);
}

public interface WebService1SoapChannel : WebService1Soap, System.ServiceModel.IClientChannel {
}

public class WebService1SoapClient : System.ServiceModel.ClientBase<WebService1Soap>, WebService1Soap {
    
    public WebService1SoapClient() {
    }
    
    public WebService1SoapClient(string endpointConfigurationName) : 
            base(endpointConfigurationName) {
    }
    
    public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress) {
    }
    
    public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress) {
    }
    
    public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress endpoint) : 
            base(binding, endpoint) {
    }
    
    public string Responding(string sCompanyID, string sDeviceID, decimal dLatitude, decimal dLongitude) {
        return base.Channel.Responding(sCompanyID, sDeviceID, dLatitude, dLongitude);
    }
    
    public System.IAsyncResult BeginResponding(string sCompanyID, string sDeviceID, decimal dLatitude, decimal dLongitude, System.AsyncCallback asyncCallback, object userState) {
        return base.Channel.BeginResponding(sCompanyID, sDeviceID, dLatitude, dLongitude, asyncCallback, userState);
    }
    
    public string EndResponding(System.IAsyncResult result) {
        return base.Channel.EndResponding(result);
    }
}
namespace tempuri.org {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Responding", Namespace="http://tempuri.org/")]
    public partial class Responding : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string sCompanyIDField;
        
        private string sDeviceIDField;
        
        private decimal dLatitudeField;
        
        private decimal dLongitudeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string sCompanyID {
            get {
                return this.sCompanyIDField;
            }
            set {
                this.sCompanyIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string sDeviceID {
            get {
                return this.sDeviceIDField;
            }
            set {
                this.sDeviceIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public decimal dLatitude {
            get {
                return this.dLatitudeField;
            }
            set {
                this.dLatitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public decimal dLongitude {
            get {
                return this.dLongitudeField;
            }
            set {
                this.dLongitudeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespondingResponse", Namespace="http://tempuri.org/")]
    public partial class RespondingResponse : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string RespondingResultField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RespondingResult {
            get {
                return this.RespondingResultField;
            }
            set {
                this.RespondingResultField = value;
            }
        }
    }
}
