// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Responder.Droid.firehall.net {
    
}


[System.ServiceModel.ServiceContractAttribute(Namespace="Responder.Droid.firehall.net", ConfigurationName="WebService1Soap")]
public interface WebService1Soap {
    
    [System.ServiceModel.OperationContractAttribute(Action="*", ReplyAction="http://tempuri.org/Test")]
    tempuri.org.WS_Output Test(string sInput, int iVersion, int iSubVersion);
    
    [System.ServiceModel.OperationContractAttribute(Action="*", ReplyAction="http://tempuri.org/Test", AsyncPattern=true)]
    System.IAsyncResult BeginTest(string sInput, int iVersion, int iSubVersion, System.AsyncCallback asyncCallback, object userState);
    
    tempuri.org.WS_Output EndTest(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(Action="*", ReplyAction="http://tempuri.org/Register")]
    tempuri.org.WS_Output Register(int iVersion, int iSubVersion, string sFireHallRespondID, string sStaffRespondID, string sDeviceIdentifier);
    
    [System.ServiceModel.OperationContractAttribute(Action="*", ReplyAction="http://tempuri.org/Register", AsyncPattern=true)]
    System.IAsyncResult BeginRegister(int iVersion, int iSubVersion, string sFireHallRespondID, string sStaffRespondID, string sDeviceIdentifier, System.AsyncCallback asyncCallback, object userState);
    
    tempuri.org.WS_Output EndRegister(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(Action="*", ReplyAction="http://tempuri.org/Login")]
    tempuri.org.WS_Output Login(int iVersion, int iSubVersion, string sFireHallRespondID, string sStaffRespondID, string sDeviceIdentifier);
    
    [System.ServiceModel.OperationContractAttribute(Action="*", ReplyAction="http://tempuri.org/Login", AsyncPattern=true)]
    System.IAsyncResult BeginLogin(int iVersion, int iSubVersion, string sFireHallRespondID, string sStaffRespondID, string sDeviceIdentifier, System.AsyncCallback asyncCallback, object userState);
    
    tempuri.org.WS_Output EndLogin(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(Action="*", ReplyAction="http://tempuri.org/Responding")]
    tempuri.org.WS_Output Responding(int iVersion, int iSubVersion, string sDeviceIdentifier, decimal dLatitude, decimal dLongitude);
    
    [System.ServiceModel.OperationContractAttribute(Action="*", ReplyAction="http://tempuri.org/Responding", AsyncPattern=true)]
    System.IAsyncResult BeginResponding(int iVersion, int iSubVersion, string sDeviceIdentifier, decimal dLatitude, decimal dLongitude, System.AsyncCallback asyncCallback, object userState);
    
    tempuri.org.WS_Output EndResponding(System.IAsyncResult result);
}

public interface WebService1SoapChannel : WebService1Soap, System.ServiceModel.IClientChannel {
}

public class WebService1SoapClient : System.ServiceModel.ClientBase<WebService1Soap>, WebService1Soap {
    
    public WebService1SoapClient() {
    }
    
    public WebService1SoapClient(string endpointConfigurationName) : 
            base(endpointConfigurationName) {
    }
    
    public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress) {
    }
    
    public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress) {
    }
    
    public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress endpoint) : 
            base(binding, endpoint) {
    }
    
    public tempuri.org.WS_Output Test(string sInput, int iVersion, int iSubVersion) {
        return base.Channel.Test(sInput, iVersion, iSubVersion);
    }
    
    public System.IAsyncResult BeginTest(string sInput, int iVersion, int iSubVersion, System.AsyncCallback asyncCallback, object userState) {
        return base.Channel.BeginTest(sInput, iVersion, iSubVersion, asyncCallback, userState);
    }
    
    public tempuri.org.WS_Output EndTest(System.IAsyncResult result) {
        return base.Channel.EndTest(result);
    }
    
    public tempuri.org.WS_Output Register(int iVersion, int iSubVersion, string sFireHallRespondID, string sStaffRespondID, string sDeviceIdentifier) {
        return base.Channel.Register(iVersion, iSubVersion, sFireHallRespondID, sStaffRespondID, sDeviceIdentifier);
    }
    
    public System.IAsyncResult BeginRegister(int iVersion, int iSubVersion, string sFireHallRespondID, string sStaffRespondID, string sDeviceIdentifier, System.AsyncCallback asyncCallback, object userState) {
        return base.Channel.BeginRegister(iVersion, iSubVersion, sFireHallRespondID, sStaffRespondID, sDeviceIdentifier, asyncCallback, userState);
    }
    
    public tempuri.org.WS_Output EndRegister(System.IAsyncResult result) {
        return base.Channel.EndRegister(result);
    }
    
    public tempuri.org.WS_Output Login(int iVersion, int iSubVersion, string sFireHallRespondID, string sStaffRespondID, string sDeviceIdentifier) {
        return base.Channel.Login(iVersion, iSubVersion, sFireHallRespondID, sStaffRespondID, sDeviceIdentifier);
    }
    
    public System.IAsyncResult BeginLogin(int iVersion, int iSubVersion, string sFireHallRespondID, string sStaffRespondID, string sDeviceIdentifier, System.AsyncCallback asyncCallback, object userState) {
        return base.Channel.BeginLogin(iVersion, iSubVersion, sFireHallRespondID, sStaffRespondID, sDeviceIdentifier, asyncCallback, userState);
    }
    
    public tempuri.org.WS_Output EndLogin(System.IAsyncResult result) {
        return base.Channel.EndLogin(result);
    }
    
    public tempuri.org.WS_Output Responding(int iVersion, int iSubVersion, string sDeviceIdentifier, decimal dLatitude, decimal dLongitude) {
        return base.Channel.Responding(iVersion, iSubVersion, sDeviceIdentifier, dLatitude, dLongitude);
    }
    
    public System.IAsyncResult BeginResponding(int iVersion, int iSubVersion, string sDeviceIdentifier, decimal dLatitude, decimal dLongitude, System.AsyncCallback asyncCallback, object userState) {
        return base.Channel.BeginResponding(iVersion, iSubVersion, sDeviceIdentifier, dLatitude, dLongitude, asyncCallback, userState);
    }
    
    public tempuri.org.WS_Output EndResponding(System.IAsyncResult result) {
        return base.Channel.EndResponding(result);
    }
}
namespace tempuri.org {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Test", Namespace="http://tempuri.org/")]
    public partial class Test : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string sInputField;
        
        private int iVersionField;
        
        private int iSubVersionField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string sInput {
            get {
                return this.sInputField;
            }
            set {
                this.sInputField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int iVersion {
            get {
                return this.iVersionField;
            }
            set {
                this.iVersionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int iSubVersion {
            get {
                return this.iSubVersionField;
            }
            set {
                this.iSubVersionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TestResponse", Namespace="http://tempuri.org/")]
    public partial class TestResponse : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private tempuri.org.WS_Output TestResultField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public tempuri.org.WS_Output TestResult {
            get {
                return this.TestResultField;
            }
            set {
                this.TestResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WS_Output", Namespace="http://tempuri.org/")]
    public partial class WS_Output : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private tempuri.org.WS_Result ResultField;
        
        private string ErrorMessageField;
        
        private tempuri.org.WS_Response MyResponseField;
        
        private tempuri.org.WS_Response[] ResponsesField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public tempuri.org.WS_Result Result {
            get {
                return this.ResultField;
            }
            set {
                this.ResultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                this.ErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public tempuri.org.WS_Response MyResponse {
            get {
                return this.MyResponseField;
            }
            set {
                this.MyResponseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public tempuri.org.WS_Response[] Responses {
            get {
                return this.ResponsesField;
            }
            set {
                this.ResponsesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WS_Response", Namespace="http://tempuri.org/")]
    public partial class WS_Response : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string FullNameField;
        
        private string TimeToHallField;
        
        private string DistanceToHallField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                this.FullNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TimeToHall {
            get {
                return this.TimeToHallField;
            }
            set {
                this.TimeToHallField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DistanceToHall {
            get {
                return this.DistanceToHallField;
            }
            set {
                this.DistanceToHallField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WS_Result", Namespace="http://tempuri.org/")]
    public enum WS_Result : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OK = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Upgrade = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AtHall = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Register", Namespace="http://tempuri.org/")]
    public partial class Register : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int iVersionField;
        
        private int iSubVersionField;
        
        private string sFireHallRespondIDField;
        
        private string sStaffRespondIDField;
        
        private string sDeviceIdentifierField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int iVersion {
            get {
                return this.iVersionField;
            }
            set {
                this.iVersionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int iSubVersion {
            get {
                return this.iSubVersionField;
            }
            set {
                this.iSubVersionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sFireHallRespondID {
            get {
                return this.sFireHallRespondIDField;
            }
            set {
                this.sFireHallRespondIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sStaffRespondID {
            get {
                return this.sStaffRespondIDField;
            }
            set {
                this.sStaffRespondIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string sDeviceIdentifier {
            get {
                return this.sDeviceIdentifierField;
            }
            set {
                this.sDeviceIdentifierField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegisterResponse", Namespace="http://tempuri.org/")]
    public partial class RegisterResponse : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private tempuri.org.WS_Output RegisterResultField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public tempuri.org.WS_Output RegisterResult {
            get {
                return this.RegisterResultField;
            }
            set {
                this.RegisterResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Login", Namespace="http://tempuri.org/")]
    public partial class Login : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int iVersionField;
        
        private int iSubVersionField;
        
        private string sFireHallRespondIDField;
        
        private string sStaffRespondIDField;
        
        private string sDeviceIdentifierField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int iVersion {
            get {
                return this.iVersionField;
            }
            set {
                this.iVersionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int iSubVersion {
            get {
                return this.iSubVersionField;
            }
            set {
                this.iSubVersionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sFireHallRespondID {
            get {
                return this.sFireHallRespondIDField;
            }
            set {
                this.sFireHallRespondIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sStaffRespondID {
            get {
                return this.sStaffRespondIDField;
            }
            set {
                this.sStaffRespondIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string sDeviceIdentifier {
            get {
                return this.sDeviceIdentifierField;
            }
            set {
                this.sDeviceIdentifierField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginResponse", Namespace="http://tempuri.org/")]
    public partial class LoginResponse : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private tempuri.org.WS_Output LoginResultField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public tempuri.org.WS_Output LoginResult {
            get {
                return this.LoginResultField;
            }
            set {
                this.LoginResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Responding", Namespace="http://tempuri.org/")]
    public partial class Responding : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int iVersionField;
        
        private int iSubVersionField;
        
        private string sDeviceIdentifierField;
        
        private decimal dLatitudeField;
        
        private decimal dLongitudeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int iVersion {
            get {
                return this.iVersionField;
            }
            set {
                this.iVersionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int iSubVersion {
            get {
                return this.iSubVersionField;
            }
            set {
                this.iSubVersionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sDeviceIdentifier {
            get {
                return this.sDeviceIdentifierField;
            }
            set {
                this.sDeviceIdentifierField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public decimal dLatitude {
            get {
                return this.dLatitudeField;
            }
            set {
                this.dLatitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public decimal dLongitude {
            get {
                return this.dLongitudeField;
            }
            set {
                this.dLongitudeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespondingResponse", Namespace="http://tempuri.org/")]
    public partial class RespondingResponse : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private tempuri.org.WS_Output RespondingResultField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public tempuri.org.WS_Output RespondingResult {
            get {
                return this.RespondingResultField;
            }
            set {
                this.RespondingResultField = value;
            }
        }
    }
}
